/* Generated By:JavaCC: Do not edit this line. ParserGrammarTokenManager.java */
package edu.buffalo.cse.sql.parser;
import java.util.ArrayList;
import java.util.Map;
import java.util.List;
import java.io.File;
import edu.buffalo.cse.sql.Schema;
import edu.buffalo.cse.sql.data.Datum;
import edu.buffalo.cse.sql.plan.*;
import edu.buffalo.cse.sql.io.Readtable;
import java.util.regex.*;
import java.io.FileNotFoundException;

/** Token Manager. */
public class ParserGrammarTokenManager implements ParserGrammarConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x91b3c0L) != 0L)
         {
            jjmatchedKind = 33;
            return 99;
         }
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 33;
            return 4;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 33;
            return 47;
         }
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 33;
            return 52;
         }
         if ((active0 & 0x420L) != 0L)
         {
            jjmatchedKind = 33;
            return 62;
         }
         if ((active0 & 0x2L) != 0L)
            return 40;
         return -1;
      case 1:
         if ((active0 & 0x91bfe0L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 99;
         }
         if ((active0 & 0x24000L) != 0L)
            return 99;
         return -1;
      case 2:
         if ((active0 & 0x900400L) != 0L)
            return 99;
         if ((active0 & 0x13be0L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 99;
         }
         return -1;
      case 3:
         if ((active0 & 0x11ae0L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 3;
            return 99;
         }
         if ((active0 & 0x2100L) != 0L)
            return 99;
         return -1;
      case 4:
         if ((active0 & 0x820L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
            return 99;
         }
         if ((active0 & 0x11240L) != 0L)
            return 99;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 32:
         return jjStartNfaWithStates_0(0, 1, 40);
      case 44:
         return jjStopAtPos(0, 27);
      case 46:
         return jjStopAtPos(0, 36);
      case 59:
         return jjStopAtPos(0, 35);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x420L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x180L);
      case 74:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x100000L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x10200L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x800L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L);
      case 78:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(1, 14, 99);
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x102000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0xa0L);
      case 83:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(1, 17, 99);
         return jjMoveStringLiteralDfa2_0(active0, 0x600L);
      case 89:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(2, 15);
         break;
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x1020L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x12200L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x900L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      case 84:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 20, 99);
         break;
      case 86:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(2, 10, 99);
         break;
      case 116:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 23, 99);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 69:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 99);
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 77:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 78:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 13, 99);
         return jjMoveStringLiteralDfa4_0(active0, 0x200L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 32:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(4, 7);
         break;
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 69:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 99);
         else if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 99);
         break;
      case 71:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 99);
         break;
      case 78:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 16, 99);
         break;
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(5, 5, 99);
         break;
      case 84:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(5, 11, 99);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 99;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 52:
                  if (curChar == 39)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(97);
                  }
                  else if (curChar == 47)
                     jjCheckNAddTwoStates(85, 86);
                  if (curChar == 39)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 47:
                  if (curChar == 39)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(97);
                  }
                  else if (curChar == 47)
                     jjCheckNAddTwoStates(85, 86);
                  if (curChar == 39)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 40:
                  if (curChar == 62)
                     jjCheckNAdd(41);
                  if (curChar == 62)
                     jjCheckNAdd(39);
                  break;
               case 99:
                  if (curChar == 39)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(97);
                  }
                  else if (curChar == 47)
                     jjCheckNAddTwoStates(85, 86);
                  if (curChar == 39)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 62:
                  if (curChar == 39)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(97);
                  }
                  else if (curChar == 47)
                     jjCheckNAddTwoStates(85, 86);
                  if (curChar == 39)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 4:
                  if (curChar == 39)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(97);
                  }
                  else if (curChar == 47)
                     jjCheckNAddTwoStates(85, 86);
                  if (curChar == 39)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 30)
                        kind = 30;
                     jjCheckNAddStates(0, 3);
                  }
                  else if ((0xac0000000000L & l) != 0L)
                  {
                     if (kind > 28)
                        kind = 28;
                  }
                  else if ((0x30000000000L & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                  }
                  else if (curChar == 39)
                     jjCheckNAddStates(4, 7);
                  else if (curChar == 60)
                     jjCheckNAddTwoStates(39, 44);
                  else if (curChar == 32)
                     jjAddStates(8, 9);
                  else if (curChar == 61)
                  {
                     if (kind > 21)
                        kind = 21;
                  }
                  if (curChar == 45)
                     jjCheckNAddStates(10, 12);
                  break;
               case 3:
                  if (curChar == 32 && kind > 18)
                     kind = 18;
                  break;
               case 8:
                  if ((0x30000000000L & l) != 0L)
                     kind = 19;
                  break;
               case 9:
               case 41:
                  if (curChar == 61 && kind > 21)
                     kind = 21;
                  break;
               case 10:
                  if (curChar == 32 && kind > 24)
                     kind = 24;
                  break;
               case 32:
                  if ((0xac0000000000L & l) != 0L && kind > 28)
                     kind = 28;
                  break;
               case 38:
                  if (curChar == 32)
                     jjAddStates(8, 9);
                  break;
               case 39:
                  if (curChar == 32 && kind > 21)
                     kind = 21;
                  break;
               case 42:
                  if (curChar == 62)
                     jjCheckNAdd(41);
                  break;
               case 43:
                  if (curChar == 60)
                     jjCheckNAddTwoStates(39, 44);
                  break;
               case 44:
                  if (curChar == 32)
                     jjCheckNAdd(41);
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 30)
                     kind = 30;
                  jjCheckNAddStates(0, 3);
                  break;
               case 67:
                  if (curChar == 45)
                     jjCheckNAdd(68);
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 69:
                  if (curChar != 46)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(16, 19);
                  break;
               case 71:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(72, 73);
                  break;
               case 72:
                  if (curChar == 45)
                     jjCheckNAdd(73);
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddTwoStates(72, 73);
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(20, 24);
                  break;
               case 75:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(76, 73);
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(25, 28);
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 30)
                     kind = 30;
                  jjCheckNAdd(77);
                  break;
               case 78:
                  if (curChar == 45)
                     jjCheckNAddStates(10, 12);
                  break;
               case 79:
                  if (curChar == 39)
                     jjCheckNAddStates(4, 7);
                  break;
               case 80:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(80, 81);
                  break;
               case 83:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 84:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(85, 86);
                  break;
               case 85:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(85, 86);
                  break;
               case 88:
                  if (curChar == 39)
                     jjAddStates(29, 30);
                  break;
               case 89:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(90, 91);
                  break;
               case 90:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(90, 91);
                  break;
               case 93:
                  if (curChar != 39)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 94:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(94, 95);
                  break;
               case 97:
                  if (curChar != 39)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(97);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 52:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddStates(31, 33);
                  }
                  else if (curChar == 92)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddTwoStates(96, 97);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(34, 37);
                  else if (curChar == 92)
                     jjCheckNAddStates(38, 40);
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 56;
                  else if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 47:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddStates(31, 33);
                  }
                  else if (curChar == 92)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddTwoStates(96, 97);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(34, 37);
                  else if (curChar == 92)
                     jjCheckNAddStates(38, 40);
                  if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 48;
                  else if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 99:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddStates(31, 33);
                  }
                  else if (curChar == 92)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddTwoStates(96, 97);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(34, 37);
                  else if (curChar == 92)
                     jjCheckNAddStates(38, 40);
                  break;
               case 62:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddStates(31, 33);
                  }
                  else if (curChar == 92)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddTwoStates(96, 97);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(34, 37);
                  else if (curChar == 92)
                     jjCheckNAddStates(38, 40);
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 64;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 4:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddStates(31, 33);
                  }
                  else if (curChar == 92)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddTwoStates(96, 97);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(34, 37);
                  else if (curChar == 92)
                     jjCheckNAddStates(38, 40);
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 2:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAddStates(41, 47);
                  }
                  if (curChar == 67)
                     jjAddStates(48, 49);
                  else if (curChar == 83)
                     jjAddStates(50, 51);
                  else if (curChar == 65)
                     jjAddStates(52, 53);
                  else if (curChar == 77)
                     jjAddStates(54, 55);
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 30;
                  else if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 26;
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 14;
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 4;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 0:
                  if (curChar == 100 && kind > 18)
                     kind = 18;
                  break;
               case 1:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 5:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 114 && kind > 18)
                     kind = 18;
                  break;
               case 7:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 11:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 101 && kind > 24)
                     kind = 24;
                  break;
               case 17:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 103 && kind > 25)
                     kind = 25;
                  break;
               case 23:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 114 && kind > 26)
                     kind = 26;
                  break;
               case 29:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 33:
                  if (curChar == 77)
                     jjAddStates(54, 55);
                  break;
               case 34:
                  if (curChar == 88 && kind > 22)
                     kind = 22;
                  break;
               case 35:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 78 && kind > 22)
                     kind = 22;
                  break;
               case 37:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 45:
                  if (curChar == 65)
                     jjAddStates(52, 53);
                  break;
               case 46:
                  if (curChar == 68 && kind > 18)
                     kind = 18;
                  break;
               case 48:
                  if (curChar == 71 && kind > 22)
                     kind = 22;
                  break;
               case 49:
                  if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 83)
                     jjAddStates(50, 51);
                  break;
               case 51:
                  if (curChar == 77 && kind > 22)
                     kind = 22;
                  break;
               case 53:
                  if (curChar == 71 && kind > 25)
                     kind = 25;
                  break;
               case 54:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 67)
                     jjAddStates(48, 49);
                  break;
               case 59:
                  if (curChar == 84 && kind > 22)
                     kind = 22;
                  break;
               case 60:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 63:
                  if (curChar == 82 && kind > 26)
                     kind = 26;
                  break;
               case 64:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 70:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(56, 58);
                  break;
               case 81:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(34, 37);
                  break;
               case 82:
                  if (curChar == 92)
                     jjCheckNAddStates(38, 40);
                  break;
               case 86:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(59, 62);
                  break;
               case 87:
                  if (curChar == 92)
                     jjCheckNAddStates(63, 65);
                  break;
               case 91:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAddStates(66, 68);
                  break;
               case 92:
                  if (curChar != 92)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAddTwoStates(92, 93);
                  break;
               case 95:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAddStates(31, 33);
                  break;
               case 96:
                  if (curChar != 92)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAddTwoStates(96, 97);
                  break;
               case 98:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAddStates(41, 47);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 99 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   67, 68, 69, 77, 80, 81, 94, 95, 40, 42, 67, 68, 77, 67, 68, 69, 
   70, 71, 74, 75, 70, 71, 72, 73, 74, 70, 71, 72, 74, 88, 89, 95, 
   96, 97, 81, 82, 83, 84, 82, 83, 84, 81, 82, 83, 84, 95, 96, 97, 
   62, 65, 52, 57, 47, 49, 35, 37, 71, 72, 73, 86, 87, 88, 89, 87, 
   88, 89, 91, 92, 93, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\103\122\105\101\124\105", 
"\124\101\102\114\105", "\106\122\117\115\40", "\106\111\114\105", "\125\123\111\116\107", 
"\103\123\126", "\123\105\114\105\103\124", "\127\110\105\122\105", "\112\117\111\116", 
"\117\116", "\102\131\40", "\125\116\111\117\116", "\101\123", null, null, "\116\117\124", 
null, null, "\151\156\164", null, null, null, "\54", null, null, null, null, null, 
null, null, "\73", "\56", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1b7fffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[99];
static private final int[] jjstateSet = new int[198];
static protected char curChar;
/** Constructor. */
public ParserGrammarTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public ParserGrammarTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 99; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
