/* Generated By:JavaCC: Do not edit this line. ParserGrammarConstants.java */
package edu.buffalo.cse.sql.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_CREATE = 5;
  /** RegularExpression Id. */
  int K_TABLE = 6;
  /** RegularExpression Id. */
  int K_FROM = 7;
  /** RegularExpression Id. */
  int K_FILE = 8;
  /** RegularExpression Id. */
  int K_USING = 9;
  /** RegularExpression Id. */
  int K_CSV = 10;
  /** RegularExpression Id. */
  int K_SELECT = 11;
  /** RegularExpression Id. */
  int K_WHERE = 12;
  /** RegularExpression Id. */
  int K_JOIN = 13;
  /** RegularExpression Id. */
  int K_ON = 14;
  /** RegularExpression Id. */
  int K_BY = 15;
  /** RegularExpression Id. */
  int K_UNION = 16;
  /** RegularExpression Id. */
  int K_AS = 17;
  /** RegularExpression Id. */
  int K_AND = 18;
  /** RegularExpression Id. */
  int K_PAR = 19;
  /** RegularExpression Id. */
  int K_NOT = 20;
  /** RegularExpression Id. */
  int K_COMPARE = 21;
  /** RegularExpression Id. */
  int K_AGG = 22;
  /** RegularExpression Id. */
  int K_INT = 23;
  /** RegularExpression Id. */
  int K_FLOAT = 24;
  /** RegularExpression Id. */
  int K_STRING = 25;
  /** RegularExpression Id. */
  int K_CHAR = 26;
  /** RegularExpression Id. */
  int K_COMMA = 27;
  /** RegularExpression Id. */
  int CAL = 28;
  /** RegularExpression Id. */
  int FLOAT = 29;
  /** RegularExpression Id. */
  int INTEGER = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int FILEPATH = 32;
  /** RegularExpression Id. */
  int LETTER = 33;
  /** RegularExpression Id. */
  int LETTERzero = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"FROM \"",
    "\"FILE\"",
    "\"USING\"",
    "\"CSV\"",
    "\"SELECT\"",
    "\"WHERE\"",
    "\"JOIN\"",
    "\"ON\"",
    "\"BY \"",
    "\"UNION\"",
    "\"AS\"",
    "<K_AND>",
    "<K_PAR>",
    "\"NOT\"",
    "<K_COMPARE>",
    "<K_AGG>",
    "\"int\"",
    "<K_FLOAT>",
    "<K_STRING>",
    "<K_CHAR>",
    "\",\"",
    "<CAL>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<FILEPATH>",
    "<LETTER>",
    "<LETTERzero>",
    "\";\"",
    "\".\"",
  };

}
